### ISSUE TITLE
[BUG] Unable to install eww with yay -S eww

### ISSUE THREAD

**Issue by mylinuxforwork** [elkowar/eww#1141]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

When I try to install eww with 

`yay -S eww `

I got compilation errors. See screenshot below. Not able to install eww.

### Reproducing the issue

Install eww on Arch based distros with

`yay -S eww`

### Expected behaviour

eww should be installed correctly with

`yay -S eww`

### Additional context

![image](https://github.com/user-attachments/assets/75913ffe-f8fc-47b6-8180-17849943f444)

**Comment by pSwaqtch** [comment]
![20240727_14h10m23s_grim](https://github.com/user-attachments/assets/b0ee0fd9-ff84-4fae-945d-73306411319c)

same issue

**Comment by pSwaqtch** [comment]
same issue, different log
![20240727_14h10m23s_grim](https://github.com/user-attachments/assets/ce6f7d5a-b42c-4d2a-87dd-5d31c0a405d1)

**Comment by mylinuxforwork** [comment]
Also the manual build as described here failed with the same error:

https://elkowar.github.io/eww/

**Comment by ovalkonia** [comment]
You are most likely trying to compile it using the `nightly` Rust toolchain, which causes the problem. Switch to `stable` using `rustup` and the problem should be gone.

List all the toolchains using `rustup toolchain list`. If you don't have `stable` installed, you can install it with `rustup toolchain install stable`. Then, just set it as the default using `rustup default stable`.

You still might have the nightly toolchain used for the `eww` directory. Unset it using `rustup override unset` in your directory, or even just uninstall the redundant toolchains if you wish.

**Comment by mylinuxforwork** [comment]
Thanks for your feedback. But I need to automate the installation of eww for my users. Many users have reported this issue and no one found a way to install right now.

You mentioned it is due to the nightly build. Is it possible that this will be fixed in a few days? 

What is your recommendation to provide a mid term way to install eww?

**Comment by L4FeeR** [comment]
I am also faced this rn, how can I fix it, although am newbie :)

**Comment by w-lfchen** [comment]
@mylinuxforwork this seems like a packaging/compilation issue, not an issue with eww itself to me.
I don't know your situation, but you might be able to automate things using a simple shell script that sets/installs the correct toolchain and then installs eww.
There is also the option of using nix, but this might be a bit too complicated for this issue.

**Comment by Me77111** [comment]
@w-lfchen the issue persists even when doing a manual install with the stable toolchain.

**Comment by mylinuxforwork** [comment]
> @mylinuxforwork this seems like a packaging/compilation issue, not an issue with eww itself to me.
> 
> I don't know your situation, but you might be able to automate things using a simple shell script that sets/installs the correct toolchain and then installs eww.
> 
> There is also the option of using nix, but this might be a bit too complicated for this issue.
> 
> 
> 
> @L4FeeR I think your best bet would be a manual install, making use of the advice @ovalkonia provided.
> 
> To me it seems like the issue stems from the fact that eww switched from the unstable nightly toolchain to the stable toolchain, so compiling eww needs to switch as well.

Please update to the latest version of the dotfiles. I have replaced eww with ags and have introduced a new ags based sidebar. I have monitored so many installation issues with eww in the last months which drives me to the replacement decision.

**Comment by mylinuxforwork** [comment]
> @w-lfchen the issue persists even when doing a manual install with the stable toolchain.

Please update to the latest version of the dotfiles. I have replaced eww with ags and have introduced a new ags based sidebar. I have monitored so many installation issues with eww in the last months which drives me to the replacement decision.

**Comment by w-lfchen** [comment]
> @w-lfchen the issue persists even when doing a manual install with the stable toolchain.

which version are you using?
Everything works fine when using the nix development shell (v1.76.0).

**Comment by ovalkonia** [comment]
`Eww` uses `rust-toolchain.toml` file to override what toolchain is used for compilation. Although, AUR package sets the `RUSTUP_TOOLCHAIN` environmental variable to `stable` before compilation. This variable has higher priority than `rust-toolchain.toml` file and therefore is preferred, causing the LATEST stable toolchain to be used, which is `1.80.0`.

I may be wrong, but I think that's what's happening here. I managed to get it working by removing two redundant lines in the PKGBUILD file.

**Comment by w-lfchen** [comment]
@ovalkonia you could file a pr against their pkgbuild, it can be found [here](https://github.com/eclairevoyant/aur-packages/blob/main/eww/PKGBUILD) if I'm not mistaken, I don't know anything about those sadly.
I assume the same problem also exists for the eww-git package, so maybe file the same change there as well.

**Comment by ovalkonia** [comment]
> @ovalkonia you could file a pr against their pkgbuild, it can be found [here](https://github.com/eclairevoyant/aur-packages/blob/main/eww/PKGBUILD) if I'm not mistaken, I don't know anything about those sadly.
> I assume the same problem also exists for the eww-git package, so maybe file the same change there as well.

Oh, right. Thank you, will try that! I don't know much about it either, but well, hope it will resolve the issue.

**Comment by larkjkj** [comment]
On yay, you need to run:
`yay --editmenu -S eww`

Will appear an option to edit the PKGBUILD, edit both  `RUST_TOOLCHAIN ` in and `prepare()` `build()`, to 1.76.0, save it and you're done.

**Comment by Eugenenoble2005** [comment]
> On yay, you need to run: `yay --editmenu -S eww`
> 
> Will appear an option to edit the PKGBUILD, edit both `RUST_TOOLCHAIN ` in and `prepare()` `build()`, to 1.76.0, save it and you're done.

In addition to this you need to modify the build instructions in your PKGBUILD in the prepare and build methods like so:
```
cargo +1.76.0 build --release
```

**Comment by GnomedDev** [comment]
The issue here isn't with the Rust version, the issue is that `Cargo.lock` is outdated. A simple `cargo update` on the library's `Cargo.lock` will fix this.

**Comment by w-lfchen** [comment]
i'd argue it's both.
the outdated `time` dependency is no issue on rust versions before 1.80.0, so building with those versions works just fine.
if you build while disregarding the [toolchain file](https://github.com/elkowar/eww/blob/4d55e9ad63d1fae887726dffcd25a32def23d34f/rust-toolchain.toml), that's an issue on your end, not eww's imo since it's there for a reason.
despite this, i'm still in favor of updating everything, see #1144.

**Comment by w-lfchen** [comment]
fixed by https://github.com/eclairevoyant/aur-packages/commit/09428eda1baccfaf481cc3eb8cfaff39b5f15012

**Comment by ovalkonia** [comment]
> fixed by [eclairevoyant/aur-packages@09428ed](https://github.com/eclairevoyant/aur-packages/commit/09428eda1baccfaf481cc3eb8cfaff39b5f15012)

The symptom's treated, but the problem still persists. There's no guarantees it won't happen again. And the discussion under the pr is closed now, so it still sucks

**Comment by w-lfchen** [comment]
i assume that packages should always be built with the latest rust version, in which case their fix seems to be the correct one.
i don't have a different explanation and i don't have any expertise on this topic so i won't comment on it; it's working for now and that's better than nothing
